server:
  port: 8203

mybatis-plus:
#  添加枚举扫描
  type-enums-package: com.atguigu.ssyx.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shequ-product?characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  rabbitmq:
    host: 192.168.174.130
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: CORRELATED  #发布确认模式，消息是否被成功发送到交换机
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual   #消费端手动确认

aliyun:
  endpoint: oss-cn-beijing.aliyuncs.com
  keyid: LTAI5tRd2G9hAcfpxpX3Ndd8
  keysecret: FDaVO8L8zUudlkxrHufT4Vfnkinhj0
  bucketname: ssyx-lujian
